use_frameworks!

platform :ios, '9.0'

target 'A_Section_Example' do
  pod 'A_Section', :path => '../'

  target 'A_Section_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
